In [8]:
import requests
from bs4 import BeautifulSoup

In [9]:
URL="https://sandbox.oxylabs.io/products"
res=requests.get(URL)
print(res.status_code)

200

In [10]:
soup=BeautifulSoup(res.text,"lxml")
print(soup.title)

<title>E-commerce	| Oxylabs Scraping Sandbox</title>

In [11]:
items=soup.select("div.product-card")
items

[<div class="product-card css-e8at8d eag3qlw10"><style data-emotion="css 15g2oxy">.css-15g2oxy{margin-top:1rem;}</style><div class="css-15g2oxy eag3qlw3"></div><style data-emotion="css o171kl">.css-o171kl{-webkit-text-decoration:none;text-decoration:none;color:inherit;}</style><a class="card-header css-o171kl eag3qlw2" href="/products/1"><span style="box-sizing:border-box;display:block;overflow:hidden;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0;position:relative"><span style="box-sizing:border-box;display:block;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0;padding-top:100%"></span><img alt="The_Legend_of_Zelda:_Ocarina_of_Time" class="image" data-nimg="responsive" decoding="async" src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7" style="position:absolute;top:0;left:0;bottom:0;right:0;box-sizing:border-box;padding:0;border:none;margin:auto;display:block;width:0;height:0;min-width:100%;max-width:100%;min-height:100%;max-height:100%;object-fit:cover"/><noscript><img alt="The_Legend_of_Zelda:_Ocarina_of_Time" class="image" data-nimg="responsive" decoding="async" loading="lazy" sizes="100vw" src="/assets/action-adventure.svg" srcset="/assets/action-adventure.svg 640w, /assets/action-adventure.svg 750w, /assets/action-adventure.svg 828w, /assets/action-adventure.svg 1080w, /assets/action-adventure.svg 1200w, /assets/action-adventure.svg 1920w, /assets/action-adventure.svg 2048w, /assets/action-adventure.svg 3840w" style="position:absolute;top:0;left:0;bottom:0;right:0;box-sizing:border-box;padding:0;border:none;margin:auto;display:block;width:0;height:0;min-width:100%;max-width:100%;min-height:100%;max-height:100%;object-fit:cover"/></noscript></span><style data-emotion="css 7u5e79">.css-7u5e79{margin:0.5rem 0rem;}</style><h4 class="title css-7u5e79 eag3qlw7">The Legend of Zelda: Ocarina of Time</h4></a><style data-emotion="css 8fdgzc">.css-8fdgzc{display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex;-webkit-box-flex-wrap:wrap;-webkit-flex-wrap:wrap;-ms-flex-wrap:wrap;flex-wrap:wrap;gap:4px;}</style><p class="category css-8fdgzc eag3qlw9"><style data-emotion="css 1pewyd6">.css-1pewyd6{display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex;-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;font-size:0.625rem;background-color:#fafafc;color:#818aa6;border-radius:15px;font-weight:bold;border:1px solid #e7e9f1;padding:4px 8px;}</style><span class="css-1pewyd6 eag3qlw8">Action Adventure</span><span class="css-1pewyd6 eag3qlw8"> Fantasy</span></p><style data-emotion="css 1lp4z4h">.css-1lp4z4h{display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex;}</style><div class="rating css-1lp4z4h e15c0rei0"></div><style data-emotion="css cput12">.css-cput12{font-size:0.75rem;line-height:1rem;margin:0.5rem 0rem;overflow:hidden;display:-webkit-box;-webkit-box-orient:vertical;-webkit-line-clamp:2;}</style><p class="description css-cput12 eag3qlw5">As a young boy, Link is tricked by Ganondorf, the King of the Gerudo Thieves. The evil human uses Link to gain access to the Sacred Realm, where he places his tainted hands on Triforce and transforms the beautiful Hyrulean landscape into a barren wasteland. Link is determined to fix the problems he helped to create, so with the help of Rauru he travels through time gathering the powers of the Seven Sages.</p><style data-emotion="css li4v8k">.css-li4v8k{font-weight:700;padding-bottom:1rem;font-size:20px;}</style><div class="price-wrapper css-li4v8k eag3qlw4">91,99 €</div><style data-emotion="css 13df51w">.css-13df51w{display:inline-block;-webkit-text-decoration:none;text-decoration:none;box-shadow:none;border:1px solid;cursor:pointer;font-weight:bold;outline:none;text-transform:none;text-align:center;font-family:Avalon,Arial;transition-property:color,background-color;transition-duration:0.1s;transition-timing-function:linear;width:unset;background:transparent;color:#130f35;border:1px solid #130f35;line-height:1.5;padding:0.6563rem 0.75rem;font-size:0.875rem;border-radius:5px;}.css-13df51w:disabled{opacity:0.6;cursor:not-allowed;}.css-13df51w svg{margin-right:0.5rem;}.css-13df51w svg *{transition-duration:0.1s;}.css-13df51w svg *:not([fill='none'])[fill],.css-13df51w svg *:not([fill]):not([stroke]){fill:#130f35;}.css-13df51w svg *:not([stroke='none'])[stroke]{stroke:#130f35;}.css-13df51w:hover{background:#130f35;color:#FFFFFF;}.css-13df51w:hover svg{margin-right:0.5rem;}.css-13df51w:hover svg *{transition-duration:0.1s;}.css-13df51w:hover svg *:not([fill='none'])[fill],.css-13df51w:hover svg *:not([fill]):not([stroke]){fill:#FFFFFF;}.css-13df51w:hover svg *:not([stroke='none'])[stroke]{stroke:#FFFFFF;}</style><a class="css-13df51w e1knbtv71" color="Secondary" href="" rel="noopener noreferrer" target="_blank"><style data-emotion="css 193c83t">.css-193c83t{width:100%;height:100%;display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex;-webkit-box-pack:center;-ms-flex-pack:center;-webkit-justify-content:center;justify-content:center;-webkit-align-items:center;-webkit-box-align:center;-ms-flex-align:center;align-items:center;}.css-193c83t svg{max-height:1.125rem;max-width:1.125rem;margin-right:0.5rem;}</style><span class="css-193c83t e1knbtv70">Add to Basket</span></a></div>,
 <div class="product-card css-e8at8d eag3qlw10"><div class="css-15g2oxy eag3qlw3"></div><a class="card-header css-o171kl eag3qlw2" href="/products/2"><span style="box-sizing:border-box;display:block;overflow:hidden;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0;position:relative"><span style="box-sizing:border-box;display:block;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0;padding-top:100%"></span><img alt="Super_Mario_Galaxy" class="image" data-nimg="responsive" decoding="async" src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7" style="position:absolute;top:0;left:0;bottom:0;right:0;box-sizing:border-box;padding:0;border:none;margin:auto;display:block;width:0;height:0;min-width:100%;max-width:100%;min-height:100%;max-height:100%;object-fit:cover"/><noscript><img alt="Super_Mario_Galaxy" class="image" data-nimg="responsive" decoding="async" loading="lazy" sizes="100vw" src="/assets/action.svg" srcset="/assets/action.svg 640w, /assets/action.svg 750w, /assets/action.svg 828w, /assets/action.svg 1080w, /assets/action.svg 1200w, /assets/action.svg 1920w, /assets/action.svg 2048w, /assets/action.svg 3840w" style="position:absolute;top:0;left:0;bottom:0;right:0;box-sizing:border-box;padding:0;border:none;margin:auto;display:block;width:0;height:0;min-width:100%;max-width:100%;min-height:100%;max-height:100%;object-fit:cover"/></noscript></span><h4 class="title css-7u5e79 eag3qlw7">Super Mario Galaxy</h4></a><p class="category css-8fdgzc eag3qlw9"><span class="css-1pewyd6 eag3qlw8">Action</span><span class="css-1pewyd6 eag3qlw8"> Platformer</span><span class="css-1pewyd6 eag3qlw8"> 3D</span></p><div class="rating css-1lp4z4h e15c0rei0"></div><p class="description css-cput12 eag3qlw5">[Metacritic's 2007 Wii Game of the Year] The ultimate Nintendo hero is taking the ultimate step ... out into space. Join Mario as he ushers in a new era of video games, defying gravity across all the planets in the galaxy. When some creature escapes into space with Princess Peach, Mario gives chase, exploring bizarre planets all across the galaxy. Mario, Peach and enemies new and old are here. Players run, jump and battle enemies as they explore all the planets in the galaxy. Since this game makes full use of all the features of the Wii Remote, players have to do all kinds of things to succeed: pressing buttons, swinging the Wii Remote and the Nunchuk, and even pointing at and dragging things with the pointer. Since he's in space, Mario can perform mind-bending jumps unlike anything he's done before. He'll also have a wealth of new moves that are all based around tilting, pointing and shaking the Wii Remote. Shake, tilt and point! Mario takes advantage of all the unique aspects of the Wii Remote and Nunchuk controller, unleashing new moves as players shake the controller and even point at and drag items with the pointer. [Nintendo]</p><div class="price-wrapper css-li4v8k eag3qlw4">91,99 €</div><a class="css-13df51w e1knbtv71" color="Secondary" href="" rel="noopener noreferrer" target="_blank"><span class="css-193c83t e1knbtv70">Add to Basket</span></a></div>,
 <div class="product-card css-e8at8d eag3qlw10"><div class="css-15g2oxy eag3qlw3"></div><a class="card-header css-o171kl eag3qlw2" href="/products/3"><span style="box-sizing:border-box;display:block;overflow:hidden;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0;position:relative"><span style="box-sizing:border-box;display:block;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0;padding-top:100%"></span><img alt="Super_Mario_Galaxy_2" class="image" data-nimg="responsive" decoding="async" src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7" style="position:absolute;top:0;left:0;bottom:0;right:0;box-sizing:border-box;padding:0;border:none;margin:auto;display:block;width:0;height:0;min-width:100%;max-width:100%;min-height:100%;max-height:100%;object-fit:cover"/><noscript><img alt="Super_Mario_Galaxy_2" class="image" data-nimg="responsive" decoding="async" loading="lazy" sizes="100vw" src="/assets/action.svg" srcset="/assets/action.svg 640w, /assets/action.svg 750w, /assets/action.svg 828w, /assets/action.svg 1080w, /assets/action.svg 1200w, /assets/action.svg 1920w, /assets/action.svg 2048w, /assets/action.svg 3840w" style="position:absolute;top:0;left:0;bottom:0;right:0;box-sizing:border-box;padding:0;border:none;margin:auto;display:block;width:0;height:0;min-width:100%;max-width:100%;min-height:100%;max-height:100%;object-fit:cover"/></noscript></span><h4 class="title css-7u5e79 eag3qlw7">Super Mario Galaxy 2</h4></a><p class="category css-8fdgzc eag3qlw9"><span class="css-1pewyd6 eag3qlw8">Action</span><span class="css-1pewyd6 eag3qlw8"> Platformer</span><span class="css-1pewyd6 eag3qlw8"> 3D</span></p><div class="rating css-1lp4z4h e15c0rei0"></div><p class="description css-cput12 eag3qlw5">Super Mario Galaxy 2, the sequel to the galaxy-hopping original game, includes the gravity-defying, physics-based exploration from the first game, but is loaded with entirely new galaxies and features to challenge players. On some stages, Mario can pair up with his dinosaur buddy Yoshi and use his tongue to grab items and spit them back at enemies. Players can also have fun with new items such as a drill that lets our hero tunnel through solid rock. [Nintendo]</p><div class="price-wrapper css-li4v8k eag3qlw4">91,99 €</div><a class="css-13df51w e1knbtv71" color="Secondary" href="" rel="noopener noreferrer" target="_blank"><span class="css-193c83t e1knbtv70">Add to Basket</span></a></div>,
 <div class="product-card css-e8at8d eag3qlw10"><div class="css-15g2oxy eag3qlw3"></div><a class="card-header css-o171kl eag3qlw2" href="/products/4"><span style="box-sizing:border-box;display:block;overflow:hidden;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0;position:relative"><span style="box-sizing:border-box;display:block;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0;padding-top:100%"></span><img alt="Metroid_Prime" class="image" data-nimg="responsive" decoding="async" src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7" style="position:absolute;top:0;left:0;bottom:0;right:0;box-sizing:border-box;padding:0;border:none;margin:auto;display:block;width:0;height:0;min-width:100%;max-width:100%;min-height:100%;max-height:100%;object-fit:cover"/><noscript><img alt="Metroid_Prime" class="image" data-nimg="responsive" decoding="async" loading="lazy" sizes="100vw" src="/assets/action.svg" srcset="/assets/action.svg 640w, /assets/action.svg 750w, /assets/action.svg 828w, /assets/action.svg 1080w, /assets/action.svg 1200w, /assets/action.svg 1920w, /assets/action.svg 2048w, /assets/action.svg 3840w" style="position:absolute;top:0;left:0;bottom:0;right:0;box-sizing:border-box;padding:0;border:none;margin:auto;display:block;width:0;height:0;min-width:100%;max-width:100%;min-height:100%;max-height:100%;object-fit:cover"/></noscript></span><h4 class="title css-7u5e79 eag3qlw7">Metroid Prime</h4></a><p class="category css-8fdgzc eag3qlw9"><span class="css-1pewyd6 eag3qlw8">Action</span><span class="css-1pewyd6 eag3qlw8"> Shooter</span><span class="css-1pewyd6 eag3qlw8"> First-Person</span><span class="css-1pewyd6 eag3qlw8"> Sci-Fi</span></p><div class="rating css-1lp4z4h e15c0rei0"></div><p class="description css-cput12 eag3qlw5">Samus returns in a new mission to unravel the mystery behind the ruined walls scattered across Tallon IV. In Metroid Prime, you'll play the role of this bounty hunter and view the world through her visor, which displays information ranging from current energy levels to ammunition. Equipped with a Power Beam and Gravity Suit, you must shoot locked switches, solve puzzles, and eliminate enemies. It's up to you to explore the world and recover more power-ups and weapons, which gradually open more gameplay areas.</p><div class="price-wrapper css-li4v8k eag3qlw4">89,99 €</div><a class="css-13df51w e1knbtv71" color="Secondary" href="" rel="noopener noreferrer" target="_blank"><span class="css-193c83t e1knbtv70">Add to Basket</span></a></div>,
 <div class="product-card css-e8at8d eag3qlw10"><div class="css-15g2oxy eag3qlw3"></div><a class="card-header css-o171kl eag3qlw2" href="/products/5"><span style="box-sizing:border-box;display:block;overflow:hidden;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0;position:relative"><span style="box-sizing:border-box;display:block;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0;padding-top:100%"></span><img alt="Super_Mario_Odyssey" class="image" data-nimg="responsive" decoding="async" src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7" style="position:absolute;top:0;left:0;bottom:0;right:0;box-sizing:border-box;padding:0;border:none;margin:auto;display:block;width:0;height:0;min-width:100%;max-width:100%;min-height:100%;max-height:100%;object-fit:cover"/><noscript><img alt="Super_Mario_Odyssey" class="image" data-nimg="responsive" decoding="async" loading="lazy" sizes="100vw" src="/assets/action.svg" srcset="/assets/action.svg 640w, /assets/action.svg 750w, /assets/action.svg 828w, /assets/action.svg 1080w, /assets/action.svg 1200w, /assets/action.svg 1920w, /assets/action.svg 2048w, /assets/action.svg 3840w" style="position:absolute;top:0;left:0;bottom:0;right:0;box-sizing:border-box;padding:0;border:none;margin:auto;display:block;width:0;height:0;min-width:100%;max-width:100%;min-height:100%;max-height:100%;object-fit:cover"/></noscript></span><h4 class="title css-7u5e79 eag3qlw7">Super Mario Odyssey</h4></a><p class="category css-8fdgzc eag3qlw9"><span class="css-1pewyd6 eag3qlw8">Action</span><span class="css-1pewyd6 eag3qlw8"> Platformer</span><span class="css-1pewyd6 eag3qlw8"> 3D</span></p><div class="rating css-1lp4z4h e15c0rei0"></div><p class="description css-cput12 eag3qlw5">New Evolution of Mario Sandbox-Style Gameplay. Mario embarks on a new journey through unknown worlds, running and jumping through huge 3D worlds in the first sandbox-style Mario game since Super Mario 64 and Super Mario Sunshine. Set sail between expansive worlds aboard an airship, and perform all-new actions, such as throwing Mario's cap.</p><div class="price-wrapper css-li4v8k eag3qlw4">89,99 €</div><a class="css-13df51w e1knbtv71" color="Secondary" href="" rel="noopener noreferrer" target="_blank"><span class="css-193c83t e1knbtv70">Add to Basket</span></a></div>,
 <div class="product-card css-e8at8d eag3qlw10"><div class="css-15g2oxy eag3qlw3"></div><a class="card-header css-o171kl eag3qlw2" href="/products/6"><span style="box-sizing:border-box;display:block;overflow:hidden;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0;position:relative"><span style="box-sizing:border-box;display:block;width:initial;height:initial;background:none;opacity:1;border:0;margin:0;padding:0;padding-top:100%"></span><img alt="Halo:_Combat_Evolved" class="image" data-nimg="responsive" decoding="async" src="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7" style="position:absolute;top:0;left:0;bottom:0;right:0;box-sizing:border-box;padding:0;border:none;margin:auto;display:block;width:0;height:0;min-width:100%;max-width:100%;min-height:100%;max-height:100%;object-fit:cover"/><noscript><img alt="Halo:_Combat_Evolved" class="image" data-nimg="responsive" decoding="async" loading="lazy" sizes="100vw" src="/assets/action.svg" srcset="/assets/action.svg 640w, /assets/action.svg 750w, /assets/action.svg 828w, /assets/action.svg 1080w, /assets/action.svg 1200w, /assets/action.svg 1920w, /assets/action.svg 2048w, /assets/action.svg 3840w" style="position:absolute;top:0;left:0;bottom:0;right:0;box-sizing:border-box;padding:0;border:none;margin:auto;display:block;width:0;height:0;min-width:100%;max-width:100%;min-height:100%;max-height:100%;object-fit:cover"/></noscript></span><h4 class="title css-7u5e79 eag3qlw7">Halo: Combat Evolved</h4></a><p class="category css-8fdgzc eag3qlw9"><span class="css-1pewyd6 eag3qlw8">Action</span><span class="css-1pewyd6 eag3qlw8"> Shooter</span><span class="css-1pewyd6 eag3qlw8"> First-Person</span><span class="css-1pewyd6 eag3qlw8"> Sci-Fi</span></p><div class="rating css-1lp4z4h e15c0rei0"></div><p class="description css-cput12 eag3qlw5">Enter the mysterious world of Halo, an alien planet shaped like a ring.  As mankind's super soldier Master Chief, you must uncover the secrets of Halo and fend off the attacking Covenant.  During your missions, you'll battle on foot, in vehicles, inside, and outside with alien and human weaponry.  Your objectives include attacking enemy outposts, raiding underground labs for advanced technology, rescuing fallen comrades, and sniping enemy forces.  Halo also lets you battle three other players via intense split screen combat or fight cooperatively with a friend through the single-player missions.</p><div class="price-wrapper css-li4v8k eag3qlw4">87,99 €</div><a class="css-13df51w e1knbtv71" color="Secondary" href="" rel="noopener noreferrer" target="_blank"><span class="css-193c83t e1knbtv70">Add to Basket</span></a></div>,

In [12]:
with open("data/items.html","w") as f:
    f.write(res.text)

In [13]:
e_games=[]

In [14]:
for item in items:

    title=item.select_one("h4.title").get_text()
    print(title)

    price=item.select_one("div.price-wrapper").get_text()
    print(price)

    categ=item.select_one("p.category")
    spans=categ.find_all("span")
    category=[]
    for span in spans:
        category.append(span.get_text(strip=True))
    print(category)

    description=item.select_one("p.description").get_text()
    print(description)

    link=item.select_one("a.card-header")["href"]
    full_link="https://sandbox.oxylabs.io"+link
    print(full_link)

    e_games.append([title,price,category,description,full_link])

The Legend of Zelda: Ocarina of Time
91,99 €
['Action Adventure', 'Fantasy']
As a young boy, Link is tricked by Ganondorf, the King of the Gerudo Thieves. The evil human uses Link to gain access to the Sacred Realm, where he places his tainted hands on Triforce and transforms the beautiful Hyrulean landscape into a barren wasteland. Link is determined to fix the problems he helped to create, so with the help of Rauru he travels through time gathering the powers of the Seven Sages.
https://sandbox.oxylabs.io/products/1
Super Mario Galaxy
91,99 €
['Action', 'Platformer', '3D']
[Metacritic's 2007 Wii Game of the Year] The ultimate Nintendo hero is taking the ultimate step ... out into space. Join Mario as he ushers in a new era of video games, defying gravity across all the planets in the galaxy. When some creature escapes into space with Princess Peach, Mario gives chase, exploring bizarre planets all across the galaxy. Mario, Peach and enemies new and old are here. Players run, jump and battle enemies as they explore all the planets in the galaxy. Since this game makes full use of all the features of the Wii Remote, players have to do all kinds of things to succeed: pressing buttons, swinging the Wii Remote and the Nunchuk, and even pointing at and dragging things with the pointer. Since he's in space, Mario can perform mind-bending jumps unlike anything he's done before. He'll also have a wealth of new moves that are all based around tilting, pointing and shaking the Wii Remote. Shake, tilt and point! Mario takes advantage of all the unique aspects of the Wii Remote and Nunchuk controller, unleashing new moves as players shake the controller and even point at and drag items with the pointer. [Nintendo]
https://sandbox.oxylabs.io/products/2
Super Mario Galaxy 2
91,99 €
['Action', 'Platformer', '3D']
Super Mario Galaxy 2, the sequel to the galaxy-hopping original game, includes the gravity-defying, physics-based exploration from the first game, but is loaded with entirely new galaxies and features to challenge players. On some stages, Mario can pair up with his dinosaur buddy Yoshi and use his tongue to grab items and spit them back at enemies. Players can also have fun with new items such as a drill that lets our hero tunnel through solid rock. [Nintendo]
https://sandbox.oxylabs.io/products/3
Metroid Prime
89,99 €
['Action', 'Shooter', 'First-Person', 'Sci-Fi']
Samus returns in a new mission to unravel the mystery behind the ruined walls scattered across Tallon IV. In Metroid Prime, you'll play the role of this bounty hunter and view the world through her visor, which displays information ranging from current energy levels to ammunition. Equipped with a Power Beam and Gravity Suit, you must shoot locked switches, solve puzzles, and eliminate enemies. It's up to you to explore the world and recover more power-ups and weapons, which gradually open more gameplay areas.
https://sandbox.oxylabs.io/products/4
Super Mario Odyssey
89,99 €
['Action', 'Platformer', '3D']
New Evolution of Mario Sandbox-Style Gameplay. Mario embarks on a new journey through unknown worlds, running and jumping through huge 3D worlds in the first sandbox-style Mario game since Super Mario 64 and Super Mario Sunshine. Set sail between expansive worlds aboard an airship, and perform all-new actions, such as throwing Mario's cap.
https://sandbox.oxylabs.io/products/5
Halo: Combat Evolved
87,99 €
['Action', 'Shooter', 'First-Person', 'Sci-Fi']
Enter the mysterious world of Halo, an alien planet shaped like a ring.  As mankind's super soldier Master Chief, you must uncover the secrets of Halo and fend off the attacking Covenant.  During your missions, you'll battle on foot, in vehicles, inside, and outside with alien and human weaponry.  Your objectives include attacking enemy outposts, raiding underground labs for advanced technology, rescuing fallen comrades, and sniping enemy forces.  Halo also lets you battle three other players via intense split screen combat or fight cooperatively with a friend through the single-player missions.
https://sandbox.oxylabs.io/products/6
The House in Fata Morgana - Dreams of the Revenants Edition -
83,99 €
['Adventure', 'Visual Novel']
A gothic suspense tale set in a cursed mansion. ‘The House in Fata Morgana’ is a full-length visual novel spanning nearly a millennium that deals in tragedy, human nature, and insanity. This version includes three games and more:
    1: The House in Fata Morgana: the main storyline.
    2: A Requiem for Innocence: a prequel shedding light on the origins of Fata Morgana’s terrible curse.
    3: Reincarnation: a sequel featuring the central cast members reincarnated in the present day. *The part including voices
    4: Other additional short stories.
https://sandbox.oxylabs.io/products/7
NFL 2K1
62,99 €
['Sports', 'Traditional', 'Football', 'Sim']
In the end, NFL 2K1 is a deeper, more refined version of the original game.
https://sandbox.oxylabs.io/products/8
Uncharted 2: Among Thieves
88,99 €
['Action Adventure', 'Modern', 'Linear']
Fortune hunter Nathan Drake returns in Uncharted 2: Among Thieves, a third-person action-adventure/shooter created by award-winning developer Naughty Dog. Down on his luck, Drake is lured back into the treacherous world of thieves and mercenary treasure-seekers he had sought to leave behind. When a mysterious artifact propels Drake on an expedition to find the legendary Himalayan valley of Shambhala, he finds himself embroiled in a dangerous game of cat-and-mouse against a fugitive war criminal who’s after more than just the fabled riches of the lost city. Caught in a web of deception and plunged into an increasingly deadly pursuit that tests the limits of his endurance, Drake will be forced to risk everything - but has his luck finally run out? [SCEA]
https://sandbox.oxylabs.io/products/9
Tekken 3
91,99 €
['Action', 'Fighting', '3D']
An ancient evil force has reawakened, attacking in secret and feeding on the souls of mighty warriors. To lure it out of hiding will take the greatest fighting contest the world has ever seen...Tekken 3. Some are fighting for revenge, some for honor, Ultimately, all are fighting for their lives and the fate of all mankind.
https://sandbox.oxylabs.io/products/10
The Legend of Zelda: The Wind Waker
90,99 €
['Action Adventure', 'Fantasy']
In this ninth entry in the Legend of Zelda series, Link debuts on GameCube with a fun new cel-shaded look, but the game stays true to the respected heritage of the series. The classic mix of sword-swinging action, perplexing puzzles and stirring story lines remains intact, but the stunning cel-shaded graphics give the people and places of Link's watery world a wildly artistic new look. And for the very first time, Link sails freely on the high seas. Join Link on his most epic and scenic adventure yet. Face unimaginable monsters, explore puzzling dungeons, and meet a cast of unforgettable characters as he searches for his kidnapped sister, Aryll.
https://sandbox.oxylabs.io/products/11
Gran Turismo
86,99 €
['Driving', 'Racing', 'GT / Street']
Welcome to the most advanced racing game ever created! Encounter exhilarating high-speed racing in 11 stunning environments. Feel handling agility and throttle response so convincing, the car seems to be an extension of yourself. Experience the extraordinary world of Gran Turismo!
https://sandbox.oxylabs.io/products/12
Metal Gear Solid 2: Sons of Liberty
88,99 €
['Action Adventure', 'Modern']
Since the incident on Shadow Moses Island, Metal Gear's top-secret technology has been leaked into the black market through the machinations of Revolver Ocelot. As a result, countless variations of Metal Gears have sprung up in every corner of the globe, making the weapon an increasingly common component of the armed forces of nuclear powers.
In the midst of all of this, Solid Snake, now a member of the anti-Metal Gear group "Philanthropy," has learned that a new prototype Metal Gear has been developed by the U.S. Marines and is being transported in secret to an unknown destination. To learn more about this new machine, Snake must infiltrate the transport, disguised as a tanker, as it makes its way down the Hudson River. Just as Snake is about to begin his mission, however, the ship is seized by a mysterious and well-armed group bent on stealing the new Metal Gear for their own, nefarious purposes. [Konami]
https://sandbox.oxylabs.io/products/13
Grand Theft Auto Double Pack
81,99 €
['Miscellaneous', 'Compilation']
From the dark and seedy streets of Liberty City's underworld to the glamorous hedonism of Vice City of the 1980s, the Grand Theft Auto double-pack takes you through the huge worlds of Grand Theft Auto III and it's sequel Vice City. The highly controversial Grand Theft Auto III gives you the freedom to go anywhere and jack anyone, putting the dark, intriguing and ruthless world of crime at your fingertips. Vice City is an entirely new game set in the '80s, preserving and adding to the free-roaming gameplay, cinematic graphics and immersive audio experience that made the Grand Theft Auto III so popular.
https://sandbox.oxylabs.io/products/14
Baldur's Gate II: Shadows of Amn
91,99 €
['Role-Playing', 'PC-style RPG', 'Western-Style']
An epic continuation of the story that began in "Baldur's Gate," this RPG is set along the southern portion of the Sword Coast, a detailed and rich area of the Forgotten Realms called Amn. It features 300 spells and 130-plus monster types compared to only 130 spells and 60 monster types in Baldur's Gate. [Interplay]
https://sandbox.oxylabs.io/products/15
Tetris Effect: Connected
88,99 €
['Puzzle', 'Stacking']
Tetris Effect: Connected is the original Tetris Effect with all-new co-op and competitive online and local multiplayer modes. This is Tetris like you've never seen it, or heard it, or felt it beforean incredibly addictive, unique and breathtakingly gorgeous reinvention of one of the most popular puzzle games of all time.
https://sandbox.oxylabs.io/products/16
The Legend of Zelda Collector's Edition
89,99 €
['Action Adventure', 'Fantasy']
Receive Four Complete Classic Zelda games all on one disc when you buy the Zelda GameCube Bundle: The Legend of Zelda, Zelda II - The adventure of Link, The Legend of Zelda: Ocarina of Time, The Legend of Zelda: Majora's Mask. The disc also includes: Playable Demo of the Legend of Zelda: The Wind Waker, Zelda Retrospective Movie, The Legend of Zelda: The Wind Waker Movie Preview.
https://sandbox.oxylabs.io/products/17
Gran Turismo 3: A-Spec
84,99 €
['Driving', 'Racing', 'GT / Street']
With the addition of two new courses (a downtown Tokyo circuit and the Monte Carlo Grand Prix course), an impressive range of cars (from Vipers to Cooper Minis), and a soundtrack featuring everything from Lenny Kravitz to Jimi Hendrix, this highly anticipated title is finally ready to be driven.
https://sandbox.oxylabs.io/products/18
The Legend of Zelda: A Link to the Past
90,99 €
['Action Adventure', 'Fantasy']
Now you have a link to one of the greatest adventures in The Legend of Zelda series.  The Legend of Zelda: A Link to the Past revives the classic SNES game on the Game Boy Advance and adds a new multiplayer mode.  In a Link to the Past, Link travels between the light world and the dark world, conquering fierce monsters and uncovering Hyrule's deepest secrets along the way.  Also included is Four Swords, which lets you play with up to three other players, slashing through dungeons and collecting rupees.  Whether you choose solo or competitive play, The Legend of Zelda will keep you occupied with its brain-bending puzzles and fun swashbuckling action.
https://sandbox.oxylabs.io/products/19
The Legend of Zelda: Majora's Mask
91,99 €
['Action Adventure', 'Fantasy']
Thrown into a parallel world by the mischievous actions of a possessed Skull Kid, Link finds a land in grave danger. The dark power of a relic called Majora's Mask has wreaked havoc on the citizens of Termina, but their most urgent problem is a suicidal moon crashing toward the world. Link has only 72 hours to find a way to stop its descent.
https://sandbox.oxylabs.io/products/20
The Last of Us
92,99 €
['Modern', 'Adventure', 'General', 'Action Adventure']
Twenty years after a pandemic radically transformed known civilization, infected humans run amuck and survivors kill one another for sustenance and weapons - literally whatever they can get their hands on. Joel, a salty survivor, is hired to smuggle a fourteen-year-old girl, Ellie, out of a rough military quarantine, but what begins as a simple job quickly turns into a brutal journey across the country.
https://sandbox.oxylabs.io/products/21
Persona 5 Royal
84,99 €
['Role-Playing', 'Japanese-Style']
Prepare for an all-new RPG experience in Persona 5 Royal based in the universe of the award-winning series, Persona! Don the mask of Joker and join the Phantom Thieves of Hearts. Break free from the chains of modern society and stage grand heists to infiltrate the minds of the corrupt and make them change their ways! Persona 5 Royal is packed with new characters, confidants, story depth, new locations to explore, and a new grappling hook mechanic for stealthy access to new areas. With a new semester at Shujin Academy, get ready to strengthen your abilities in the metaverse and in your daily life. Persona 5 Royal presents a unique visual style and award nominated composer Shoji Meguro returns with an all-new soundtrack. Explore Tokyo, unlock new Personas, customize your own personal Thieves Den, discover a never-before-seen story arc, cutscenes, alternate endings, and more! Even for the most seasoned Phantom Thieves among us, Persona 5 Royal is a new challenge to defy conventions, discover the power within, and fight for justice. Wear the mask. Reveal your truth.
https://sandbox.oxylabs.io/products/22
The Last of Us Remastered
92,99 €
['Action Adventure', 'General', 'Modern']
The Last of Us has been rebuilt for the PlayStation4 system. Now featuring full 1080p, higher resolution character models, improved shadows and lighting, in addition to several other gameplay improvements. 20 years after a pandemic has radically changed known civilization, infected humans run wild and survivors are killing each other for food, weapons; whatever they can get their hands on. Joel, a violent survivor, is hired to smuggle a 14 year-old girl, Ellie, out of an oppressive military quarantine zone, but what starts as a small job soon transforms into a brutal journey across the U.S. The Last of Us Remastered includes the Abandoned Territories Map Pack, Reclaimed Territories Map Pack, and the critically acclaimed The Last of Us: Left Behind Single Player campaign that combines themes of survival, loyalty, and love with tense, survival-action gameplay.

Remastered Features:
-Explore a brutal post-pandemic world, fully realized with the power of PlayStation4 system
-Includes additional game content: over $30 in value
-Delve into Ellies past in Left Behind, the single-player prequel chapter
-Eight new multiplayer maps in the Abandoned and Reclaimed Territories packs
-In-game cinematic commentary from the cast and creative director
https://sandbox.oxylabs.io/products/23
The Legend of Zelda: Ocarina of Time 3D
90,99 €
['Miscellaneous', 'Fantasy', 'Compilation', 'Action Adventure', 'Open-World']
The Legend of Zelda: Ocarina of Time 3D takes the best-reviewed game of all time for a brand-new experience. Now in 3D all of the graphic textures and colors have been vastly improved, taking advantage of the considerable graphic power of the Nintendo 3DS system. This game tells the epic story of Hyrule and Link™, Zelda™, and Ganondorf in remarkable depth and gives context to the many tales of their struggles. As such, this title represents a perfect entry point for players new to the Zelda franchise. Phenomenally Improved Graphics Beyond even the incredible 3D effect, every graphic texture and character model has been lovingly built from the ground up to create the most dynamic and vivid vision of Zelda’s kingdom yet. This is Hyrule as you’ve always imagined it. Playing the Ocarina Link needs to play the eponymous Ocarina of Time many, many times over the course of the game. This involves a specific series of button presses to play one of the twelve songs in the game. In the original title, you would need to assign the ocarina to an item slot, then likely review the button prompts to your song, then play them from memory. The Nintendo 3DS version has the ocarina constantly available on the Touch Screen, and playing with the button prompts for each song right in front of you. Enhanced Game play While the greatest care has been taken to preserve the classic game play and story, a number of new features make this the definitive version of this extraordinary game.
https://sandbox.oxylabs.io/products/24
Chrono Cross
88,99 €
['Role-Playing', 'Console-style RPG']
Featuring a storyline developed by the creator of Chrono Trigger and Xenogears, Chrono Cross has been christened the "Best RPG Creation" by its development team. With multiple scenarios cast along a single story thread, and many different endings, each replay can result in an entirely new adventure. In addition, a brand new battle system makes combat smooth and innovative by introducing an element field system and combo system that gives the player unparalleled flexibility in their fighting options. The elimination of random battles also quickens the pace of the game, and places the choice of where to battle in the player's hands. With character designs by a famed Japanese illustrator and music by the original Chrono Trigger composer, Chrono Cross features visuals and sounds that bring its magic to life.
https://sandbox.oxylabs.io/products/25
Gears of War
84,99 €
['Action', 'Shooter', 'Third-Person', 'Sci-Fi', 'Arcade']
Gears of War blends tactical action with survival horror and thrusts gamers into a deep and harrowing story of humankind's epic battle for survival against the Locust Horde, a nightmarish race of creatures that surface from the bowels of the planet. Lead war hero Marcus Fenix and his fire team as they face the onslaught of merciless warrior fiends. A revolutionary tactical combat system and breathtaking, high-definition visuals from the Unreal Engine 3 immerse you in a horrifying story of war and survival. A.I. teammates are indiscernable from human players. Voice recognition and real-time lip synching heighten the experience. The battlefield is a lethal place. To survive, suppress your enemy with blindfire, take cover in interactive environments, or use weapons and teammates to outwit your foes. [Microsoft]
https://sandbox.oxylabs.io/products/26
Sid Meier's Civilization II
88,99 €
['Strategy', 'Turn-Based', 'Historic', 'General', '4X']
An empire-building turn-based strategy game. The game starts at the Old Stone Age in 4000 BC. Your tribe begins with a Settlers unit and has no knowledge about the surrounding area. As you found new cities and explore the surroundings, you may find hostile barbarians, villages, and other competing cultures. [Civ Fantatics' Center]
https://sandbox.oxylabs.io/products/27
Halo 3
81,99 €
['Action', 'Shooter', 'First-Person', 'Sci-Fi', 'Arcade']
Halo 3 is the third game in the Halo Trilogy and provides the thrilling conclusion to the events begun in "Halo: Combat Evolved." Halo 3 picks up where "Halo 2" left off. The Master Chief is returning to Earth to finish the fight. The Covenant occupation of Earth has uncovered a massive and ancient object beneath the African sands - an object who's secrets have yet to be revealed. Earth's forces are battered and beaten. The Master Chief's AI companion Cortana is still trapped in the clutches of the Gravemind - a horrifying Flood intelligence, and a civil war is raging in the heart of the Covenant. This is how the world ends... [Bungie]
https://sandbox.oxylabs.io/products/28
Ninja Gaiden Black
88,99 €

In [15]:
e_games

[['The Legend of Zelda: Ocarina of Time',
  '91,99 €',
  ['Action Adventure', 'Fantasy'],
  'As a young boy, Link is tricked by Ganondorf, the King of the Gerudo Thieves. The evil human uses Link to gain access to the Sacred Realm, where he places his tainted hands on Triforce and transforms the beautiful Hyrulean landscape into a barren wasteland. Link is determined to fix the problems he helped to create, so with the help of Rauru he travels through time gathering the powers of the Seven Sages.',
  'https://sandbox.oxylabs.io/products/1'],
 ['Super Mario Galaxy',
  '91,99 €',
  ['Action', 'Platformer', '3D'],
  "[Metacritic's 2007 Wii Game of the Year] The ultimate Nintendo hero is taking the ultimate step ... out into space. Join Mario as he ushers in a new era of video games, defying gravity across all the planets in the galaxy. When some creature escapes into space with Princess Peach, Mario gives chase, exploring bizarre planets all across the galaxy. Mario, Peach and enemies new and old are here. Players run, jump and battle enemies as they explore all the planets in the galaxy. Since this game makes full use of all the features of the Wii Remote, players have to do all kinds of things to succeed: pressing buttons, swinging the Wii Remote and the Nunchuk, and even pointing at and dragging things with the pointer. Since he's in space, Mario can perform mind-bending jumps unlike anything he's done before. He'll also have a wealth of new moves that are all based around tilting, pointing and shaking the Wii Remote. Shake, tilt and point! Mario takes advantage of all the unique aspects of the Wii Remote and Nunchuk controller, unleashing new moves as players shake the controller and even point at and drag items with the pointer. [Nintendo]",
  'https://sandbox.oxylabs.io/products/2'],
 ['Super Mario Galaxy 2',
  '91,99 €',
  ['Action', 'Platformer', '3D'],
  'Super Mario Galaxy 2, the sequel to the galaxy-hopping original game, includes the gravity-defying, physics-based exploration from the first game, but is loaded with entirely new galaxies and features to challenge players. On some stages, Mario can pair up with his dinosaur buddy Yoshi and use his tongue to grab items and spit them back at enemies. Players can also have fun with new items such as a drill that lets our hero tunnel through solid rock. [Nintendo]',
  'https://sandbox.oxylabs.io/products/3'],
 ['Metroid Prime',
  '89,99 €',
  ['Action', 'Shooter', 'First-Person', 'Sci-Fi'],
  "Samus returns in a new mission to unravel the mystery behind the ruined walls scattered across Tallon IV. In Metroid Prime, you'll play the role of this bounty hunter and view the world through her visor, which displays information ranging from current energy levels to ammunition. Equipped with a Power Beam and Gravity Suit, you must shoot locked switches, solve puzzles, and eliminate enemies. It's up to you to explore the world and recover more power-ups and weapons, which gradually open more gameplay areas.",
  'https://sandbox.oxylabs.io/products/4'],
 ['Super Mario Odyssey',
  '89,99 €',
  ['Action', 'Platformer', '3D'],
  "New Evolution of Mario Sandbox-Style Gameplay. Mario embarks on a new journey through unknown worlds, running and jumping through huge 3D worlds in the first sandbox-style Mario game since Super Mario 64 and Super Mario Sunshine. Set sail between expansive worlds aboard an airship, and perform all-new actions, such as throwing Mario's cap.",
  'https://sandbox.oxylabs.io/products/5'],
 ['Halo: Combat Evolved',
  '87,99 €',
  ['Action', 'Shooter', 'First-Person', 'Sci-Fi'],
  "Enter the mysterious world of Halo, an alien planet shaped like a ring.  As mankind's super soldier Master Chief, you must uncover the secrets of Halo and fend off the attacking Covenant.  During your missions, you'll battle on foot, in vehicles, inside, and outside with alien and human weaponry.  Your objectives include attacking enemy outposts, raiding underground labs for advanced technology, rescuing fallen comrades, and sniping enemy forces.  Halo also lets you battle three other players via intense split screen combat or fight cooperatively with a friend through the single-player missions.",
  'https://sandbox.oxylabs.io/products/6'],
 ['The House in Fata Morgana - Dreams of the Revenants Edition -',
  '83,99 €',
  ['Adventure', 'Visual Novel'],
  'A gothic suspense tale set in a cursed mansion. ‘The House in Fata Morgana’ is a full-length visual novel spanning nearly a millennium that deals in tragedy, human nature, and insanity. This version includes three games and more:\n    1: The House in Fata Morgana: the main storyline.\n    2: A Requiem for Innocence: a prequel shedding light on the origins of Fata Morgana’s terrible curse.\n    3: Reincarnation: a sequel featuring the central cast members reincarnated in the present day. *The part including voices\n    4: Other additional short stories.',
  'https://sandbox.oxylabs.io/products/7'],
 ['NFL 2K1',
  '62,99 €',
  ['Sports', 'Traditional', 'Football', 'Sim'],
  'In the end, NFL 2K1 is a deeper, more refined version of the original game.',
  'https://sandbox.oxylabs.io/products/8'],
 ['Uncharted 2: Among Thieves',
  '88,99 €',
  ['Action Adventure', 'Modern', 'Linear'],
  'Fortune hunter Nathan Drake returns in Uncharted 2: Among Thieves, a third-person action-adventure/shooter created by award-winning developer Naughty Dog. Down on his luck, Drake is lured back into the treacherous world of thieves and mercenary treasure-seekers he had sought to leave behind. When a mysterious artifact propels Drake on an expedition to find the legendary Himalayan valley of Shambhala, he finds himself embroiled in a dangerous game of cat-and-mouse against a fugitive war criminal who’s after more than just the fabled riches of the lost city. Caught in a web of deception and plunged into an increasingly deadly pursuit that tests the limits of his endurance, Drake will be forced to risk everything - but has his luck finally run out? [SCEA]',
  'https://sandbox.oxylabs.io/products/9'],
 ['Tekken 3',
  '91,99 €',
  ['Action', 'Fighting', '3D'],
  'An ancient evil force has reawakened, attacking in secret and feeding on the souls of mighty warriors. To lure it out of hiding will take the greatest fighting contest the world has ever seen...Tekken 3. Some are fighting for revenge, some for honor, Ultimately, all are fighting for their lives and the fate of all mankind.',
  'https://sandbox.oxylabs.io/products/10'],
 ['The Legend of Zelda: The Wind Waker',
  '90,99 €',
  ['Action Adventure', 'Fantasy'],
  "In this ninth entry in the Legend of Zelda series, Link debuts on GameCube with a fun new cel-shaded look, but the game stays true to the respected heritage of the series. The classic mix of sword-swinging action, perplexing puzzles and stirring story lines remains intact, but the stunning cel-shaded graphics give the people and places of Link's watery world a wildly artistic new look. And for the very first time, Link sails freely on the high seas. Join Link on his most epic and scenic adventure yet. Face unimaginable monsters, explore puzzling dungeons, and meet a cast of unforgettable characters as he searches for his kidnapped sister, Aryll.",
  'https://sandbox.oxylabs.io/products/11'],
 ['Gran Turismo',
  '86,99 €',
  ['Driving', 'Racing', 'GT / Street'],
  'Welcome to the most advanced racing game ever created! Encounter exhilarating high-speed racing in 11 stunning environments. Feel handling agility and throttle response so convincing, the car seems to be an extension of yourself. Experience the extraordinary world of Gran Turismo!',
  'https://sandbox.oxylabs.io/products/12'],
 ['Metal Gear Solid 2: Sons of Liberty',
  '88,99 €',
  ['Action Adventure', 'Modern'],
  'Since the incident on Shadow Moses Island, Metal Gear\'s top-secret technology has been leaked into the black market through the machinations of Revolver Ocelot. As a result, countless variations of Metal Gears have sprung up in every corner of the globe, making the weapon an increasingly common component of the armed forces of nuclear powers. \nIn the midst of all of this, Solid Snake, now a member of the anti-Metal Gear group "Philanthropy," has learned that a new prototype Metal Gear has been developed by the U.S. Marines and is being transported in secret to an unknown destination. To learn more about this new machine, Snake must infiltrate the transport, disguised as a tanker, as it makes its way down the Hudson River. Just as Snake is about to begin his mission, however, the ship is seized by a mysterious and well-armed group bent on stealing the new Metal Gear for their own, nefarious purposes. [Konami]',
  'https://sandbox.oxylabs.io/products/13'],
 ['Grand Theft Auto Double Pack',
  '81,99 €',
  ['Miscellaneous', 'Compilation'],
  "From the dark and seedy streets of Liberty City's underworld to the glamorous hedonism of Vice City of the 1980s, the Grand Theft Auto double-pack takes you through the huge worlds of Grand Theft Auto III and it's sequel Vice City. The highly controversial Grand Theft Auto III gives you the freedom to go anywhere and jack anyone, putting the dark, intriguing and ruthless world of crime at your fingertips. Vice City is an entirely new game set in the '80s, preserving and adding to the free-roaming gameplay, cinematic graphics and immersive audio experience that made the Grand Theft Auto III so popular.",
  'https://sandbox.oxylabs.io/products/14'],
 ["Baldur's Gate II: Shadows of Amn",
  '91,99 €',
  ['Role-Playing', 'PC-style RPG', 'Western-Style'],
  'An epic continuation of the story that began in "Baldur\'s Gate," this RPG is set along the southern portion of the Sword Coast, a detailed and rich area of the Forgotten Realms called Amn. It features 300 spells and 130-plus monster types compared to only 130 spells and 60 monster types in Baldur\'s Gate. [Interplay]',
  'https://sandbox.oxylabs.io/products/15'],
 ['Tetris Effect: Connected',
  '88,99 €',
  ['Puzzle', 'Stacking'],
  "Tetris Effect: Connected is the original Tetris Effect with all-new co-op and competitive online and local multiplayer modes. This is Tetris like you've never seen it, or heard it, or felt it beforean incredibly addictive, unique and breathtakingly gorgeous reinvention of one of the most popular puzzle games of all time.",
  'https://sandbox.oxylabs.io/products/16'],
 ["The Legend of Zelda Collector's Edition",
  '89,99 €',
  ['Action Adventure', 'Fantasy'],
  "Receive Four Complete Classic Zelda games all on one disc when you buy the Zelda GameCube Bundle: The Legend of Zelda, Zelda II - The adventure of Link, The Legend of Zelda: Ocarina of Time, The Legend of Zelda: Majora's Mask. The disc also includes: Playable Demo of the Legend of Zelda: The Wind Waker, Zelda Retrospective Movie, The Legend of Zelda: The Wind Waker Movie Preview.",
  'https://sandbox.oxylabs.io/products/17'],
 ['Gran Turismo 3: A-Spec',
  '84,99 €',
  ['Driving', 'Racing', 'GT / Street'],
  'With the addition of two new courses (a downtown Tokyo circuit and the Monte Carlo Grand Prix course), an impressive range of cars (from Vipers to Cooper Minis), and a soundtrack featuring everything from Lenny Kravitz to Jimi Hendrix, this highly anticipated title is finally ready to be driven.',
  'https://sandbox.oxylabs.io/products/18'],
 ['The Legend of Zelda: A Link to the Past',
  '90,99 €',
  ['Action Adventure', 'Fantasy'],
  "Now you have a link to one of the greatest adventures in The Legend of Zelda series.  The Legend of Zelda: A Link to the Past revives the classic SNES game on the Game Boy Advance and adds a new multiplayer mode.  In a Link to the Past, Link travels between the light world and the dark world, conquering fierce monsters and uncovering Hyrule's deepest secrets along the way.  Also included is Four Swords, which lets you play with up to three other players, slashing through dungeons and collecting rupees.  Whether you choose solo or competitive play, The Legend of Zelda will keep you occupied with its brain-bending puzzles and fun swashbuckling action.",
  'https://sandbox.oxylabs.io/products/19'],
 ["The Legend of Zelda: Majora's Mask",
  '91,99 €',
  ['Action Adventure', 'Fantasy'],
  "Thrown into a parallel world by the mischievous actions of a possessed Skull Kid, Link finds a land in grave danger. The dark power of a relic called Majora's Mask has wreaked havoc on the citizens of Termina, but their most urgent problem is a suicidal moon crashing toward the world. Link has only 72 hours to find a way to stop its descent.",
  'https://sandbox.oxylabs.io/products/20'],
 ['The Last of Us',
  '92,99 €',
  ['Modern', 'Adventure', 'General', 'Action Adventure'],
  'Twenty years after a pandemic radically transformed known civilization, infected humans run amuck and survivors kill one another for sustenance and weapons - literally whatever they can get their hands on. Joel, a salty survivor, is hired to smuggle a fourteen-year-old girl, Ellie, out of a rough military quarantine, but what begins as a simple job quickly turns into a brutal journey across the country.',
  'https://sandbox.oxylabs.io/products/21'],
 ['Persona 5 Royal',
  '84,99 €',
  ['Role-Playing', 'Japanese-Style'],
  'Prepare for an all-new RPG experience in Persona 5 Royal based in the universe of the award-winning series, Persona! Don the mask of Joker and join the Phantom Thieves of Hearts. Break free from the chains of modern society and stage grand heists to infiltrate the minds of the corrupt and make them change their ways! Persona 5 Royal is packed with new characters, confidants, story depth, new locations to explore, and a new grappling hook mechanic for stealthy access to new areas. With a new semester at Shujin Academy, get ready to strengthen your abilities in the metaverse and in your daily life. Persona 5 Royal presents a unique visual style and award nominated composer Shoji Meguro returns with an all-new soundtrack. Explore Tokyo, unlock new Personas, customize your own personal Thieves Den, discover a never-before-seen story arc, cutscenes, alternate endings, and more! Even for the most seasoned Phantom Thieves among us, Persona 5 Royal is a new challenge to defy conventions, discover the power within, and fight for justice. Wear the mask. Reveal your truth.',
  'https://sandbox.oxylabs.io/products/22'],
 ['The Last of Us Remastered',
  '92,99 €',
  ['Action Adventure', 'General', 'Modern'],
  'The Last of Us has been rebuilt for the PlayStation4 system. Now featuring full 1080p, higher resolution character models, improved shadows and lighting, in addition to several other gameplay improvements. 20 years after a pandemic has radically changed known civilization, infected humans run wild and survivors are killing each other for food, weapons; whatever they can get their hands on. Joel, a violent survivor, is hired to smuggle a 14 year-old girl, Ellie, out of an oppressive military quarantine zone, but what starts as a small job soon transforms into a brutal journey across the U.S. The Last of Us Remastered includes the Abandoned Territories Map Pack, Reclaimed Territories Map Pack, and the critically acclaimed The Last of Us: Left Behind Single Player campaign that combines themes of survival, loyalty, and love with tense, survival-action gameplay.\n\nRemastered Features:\n-Explore a brutal post-pandemic world, fully realized with the power of PlayStation4 system\n-Includes additional game content: over $30 in value\n-Delve into Ellies past in Left Behind, the single-player prequel chapter\n-Eight new multiplayer maps in the Abandoned and Reclaimed Territories packs\n-In-game cinematic commentary from the cast and creative director',
  'https://sandbox.oxylabs.io/products/23'],
 ['The Legend of Zelda: Ocarina of Time 3D',
  '90,99 €',
  ['Miscellaneous',
   'Fantasy',
   'Compilation',
   'Action Adventure',
   'Open-World'],
  'The Legend of Zelda: Ocarina of Time 3D takes the best-reviewed game of all time for a brand-new experience. Now in 3D all of the graphic textures and colors have been vastly improved, taking advantage of the considerable graphic power of the Nintendo 3DS system. This game tells the epic story of Hyrule and Link™, Zelda™, and Ganondorf in remarkable depth and gives context to the many tales of their struggles. As such, this title represents a perfect entry point for players new to the Zelda franchise. Phenomenally Improved Graphics Beyond even the incredible 3D effect, every graphic texture and character model has been lovingly built from the ground up to create the most dynamic and vivid vision of Zelda’s kingdom yet. This is Hyrule as you’ve always imagined it. Playing the Ocarina Link needs to play the eponymous Ocarina of Time many, many times over the course of the game. This involves a specific series of button presses to play one of the twelve songs in the game. In the original title, you would need to assign the ocarina to an item slot, then likely review the button prompts to your song, then play them from memory. The Nintendo 3DS version has the ocarina constantly available on the Touch Screen, and playing with the button prompts for each song right in front of you. Enhanced Game play While the greatest care has been taken to preserve the classic game play and story, a number of new features make this the definitive version of this extraordinary game.',
  'https://sandbox.oxylabs.io/products/24'],
 ['Chrono Cross',
  '88,99 €',
  ['Role-Playing', 'Console-style RPG'],
  'Featuring a storyline developed by the creator of Chrono Trigger and Xenogears, Chrono Cross has been christened the "Best RPG Creation" by its development team. With multiple scenarios cast along a single story thread, and many different endings, each replay can result in an entirely new adventure. In addition, a brand new battle system makes combat smooth and innovative by introducing an element field system and combo system that gives the player unparalleled flexibility in their fighting options. The elimination of random battles also quickens the pace of the game, and places the choice of where to battle in the player\'s hands. With character designs by a famed Japanese illustrator and music by the original Chrono Trigger composer, Chrono Cross features visuals and sounds that bring its magic to life.',
  'https://sandbox.oxylabs.io/products/25'],
 ['Gears of War',
  '84,99 €',
  ['Action', 'Shooter', 'Third-Person', 'Sci-Fi', 'Arcade'],
  "Gears of War blends tactical action with survival horror and thrusts gamers into a deep and harrowing story of humankind's epic battle for survival against the Locust Horde, a nightmarish race of creatures that surface from the bowels of the planet. Lead war hero Marcus Fenix and his fire team as they face the onslaught of merciless warrior fiends. A revolutionary tactical combat system and breathtaking, high-definition visuals from the Unreal Engine 3 immerse you in a horrifying story of war and survival. A.I. teammates are indiscernable from human players. Voice recognition and real-time lip synching heighten the experience. The battlefield is a lethal place. To survive, suppress your enemy with blindfire, take cover in interactive environments, or use weapons and teammates to outwit your foes. [Microsoft]",
  'https://sandbox.oxylabs.io/products/26'],
 ["Sid Meier's Civilization II",
  '88,99 €',
  ['Strategy', 'Turn-Based', 'Historic', 'General', '4X'],
  "An empire-building turn-based strategy game. The game starts at the Old Stone Age in 4000 BC. Your tribe begins with a Settlers unit and has no knowledge about the surrounding area. As you found new cities and explore the surroundings, you may find hostile barbarians, villages, and other competing cultures. [Civ Fantatics' Center]",
  'https://sandbox.oxylabs.io/products/27'],
 ['Halo 3',
  '81,99 €',
  ['Action', 'Shooter', 'First-Person', 'Sci-Fi', 'Arcade'],

In [16]:
import pandas as pd

In [25]:
df=pd.DataFrame(e_games,columns=["Title","Price","Category","Description","Links"])

In [18]:
df

,Title,Price,Category,Description,Links
0,The Legend of Zelda: Ocarina of Time,"91,99 €","[Action Adventure, Fantasy]","As a young boy, Link is tricked by Ganondorf, ...",https://sandbox.oxylabs.io/products/1
1,Super Mario Galaxy,"91,99 €","[Action, Platformer, 3D]",[Metacritic's 2007 Wii Game of the Year] The u...,https://sandbox.oxylabs.io/products/2
2,Super Mario Galaxy 2,"91,99 €","[Action, Platformer, 3D]","Super Mario Galaxy 2, the sequel to the galaxy...",https://sandbox.oxylabs.io/products/3
3,Metroid Prime,"89,99 €","[Action, Shooter, First-Person, Sci-Fi]",Samus returns in a new mission to unravel the ...,https://sandbox.oxylabs.io/products/4
4,Super Mario Odyssey,"89,99 €","[Action, Platformer, 3D]",New Evolution of Mario Sandbox-Style Gameplay....,https://sandbox.oxylabs.io/products/5
5,Halo: Combat Evolved,"87,99 €","[Action, Shooter, First-Person, Sci-Fi]","Enter the mysterious world of Halo, an alien p...",https://sandbox.oxylabs.io/products/6
6,The House in Fata Morgana - Dreams of the Reve...,"83,99 €","[Adventure, Visual Novel]",A gothic suspense tale set in a cursed mansion...,https://sandbox.oxylabs.io/products/7
7,NFL 2K1,"62,99 €","[Sports, Traditional, Football, Sim]","In the end, NFL 2K1 is a deeper, more refined ...",https://sandbox.oxylabs.io/products/8
8,Uncharted 2: Among Thieves,"88,99 €","[Action Adventure, Modern, Linear]",Fortune hunter Nathan Drake returns in Unchart...,https://sandbox.oxylabs.io/products/9
9,Tekken 3,"91,99 €","[Action, Fighting, 3D]","An ancient evil force has reawakened, attackin...",https://sandbox.oxylabs.io/products/10
10,The Legend of Zelda: The Wind Waker,"90,99 €","[Action Adventure, Fantasy]",In this ninth entry in the Legend of Zelda ser...,https://sandbox.oxylabs.io/products/11
11,Gran Turismo,"86,99 €","[Driving, Racing, GT / Street]",Welcome to the most advanced racing game ever ...,https://sandbox.oxylabs.io/products/12
12,Metal Gear Solid 2: Sons of Liberty,"88,99 €","[Action Adventure, Modern]","Since the incident on Shadow Moses Island, Met...",https://sandbox.oxylabs.io/products/13
13,Grand Theft Auto Double Pack,"81,99 €","[Miscellaneous, Compilation]",From the dark and seedy streets of Liberty Cit...,https://sandbox.oxylabs.io/products/14
14,Baldur's Gate II: Shadows of Amn,"91,99 €","[Role-Playing, PC-style RPG, Western-Style]",An epic continuation of the story that began i...,https://sandbox.oxylabs.io/products/15
15,Tetris Effect: Connected,"88,99 €","[Puzzle, Stacking]",Tetris Effect: Connected is the original Tetri...,https://sandbox.oxylabs.io/products/16
16,The Legend of Zelda Collector's Edition,"89,99 €","[Action Adventure, Fantasy]",Receive Four Complete Classic Zelda games all ...,https://sandbox.oxylabs.io/products/17
17,Gran Turismo 3: A-Spec,"84,99 €","[Driving, Racing, GT / Street]",With the addition of two new courses (a downto...,https://sandbox.oxylabs.io/products/18
18,The Legend of Zelda: A Link to the Past,"90,99 €","[Action Adventure, Fantasy]",Now you have a link to one of the greatest adv...,https://sandbox.oxylabs.io/products/19
19,The Legend of Zelda: Majora's Mask,"91,99 €","[Action Adventure, Fantasy]",Thrown into a parallel world by the mischievou...,https://sandbox.oxylabs.io/products/20
20,The Last of Us,"92,99 €","[Modern, Adventure, General, Action Adventure]",Twenty years after a pandemic radically transf...,https://sandbox.oxylabs.io/products/21
21,Persona 5 Royal,"84,99 €","[Role-Playing, Japanese-Style]",Prepare for an all-new RPG experience in Perso...,https://sandbox.oxylabs.io/products/22
22,The Last of Us Remastered,"92,99 €","[Action Adventure, General, Modern]",The Last of Us has been rebuilt for the PlaySt...,https://sandbox.oxylabs.io/products/23
23,The Legend of Zelda: Ocarina of Time 3D,"90,99 €","[Miscellaneous, Fantasy, Compilation, Action A...",The Legend of Zelda: Ocarina of Time 3D takes ...,https://sandbox.oxylabs.io/products/24
24,Chrono Cross,"88,99 €","[Role-Playing, Console-style RPG]",Featuring a storyline developed by the creator...,https://sandbox.oxylabs.io/products/25
25,Gears of War,"84,99 €","[Action, Shooter, Third-Person, Sci-Fi, Arcade]",Gears of War blends tactical action with survi...,https://sandbox.oxylabs.io/products/26
26,Sid Meier's Civilization II,"88,99 €","[Strategy, Turn-Based, Historic, General, 4X]",An empire-building turn-based strategy game. T...,https://sandbox.oxylabs.io/products/27
27,Halo 3,"81,99 €","[Action, Shooter, First-Person, Sci-Fi, Arcade]",Halo 3 is the third game in the Halo Trilogy a...,https://sandbox.oxylabs.io/products/28
28,Ninja Gaiden Black,"88,99 €","[Action Adventure, Fantasy]",In Ninja Gaiden Black you can reprise the role...,https://sandbox.oxylabs.io/products/29
29,Super Mario Advance 4: Super Mario Bros. 3,"89,99 €","[Action, Platformer, 2D]","A combination of exciting platforming action, ...",https://sandbox.oxylabs.io/products/30
30,Jet Grind Radio,"83,99 €","[Action, Platformer, 3D]","Join a graffiti crew, stamp your territory and...",https://sandbox.oxylabs.io/products/31
31,Grim Fandango,"91,99 €","[Adventure, General, 3D, Third-Person, Fantasy]",Something's rotten in the Land of Dead and you...,https://sandbox.oxylabs.io/products/32

In [26]:
df.to_csv("data/games.csv",index=False)

In [20]:
df.to_json("data/games.json")

In [21]:
pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in c:\users\hp\anaconda3\lib\site-packages (9.7.0)
Note: you may need to restart the kernel to use updated packages.

In [22]:
import mysql.connector
import pandas as pd

In [27]:
# 1.Lets read csv
pd.read_csv("data/games.csv")

,Title,Price,Category,Description,Links
0,The Legend of Zelda: Ocarina of Time,"91,99 €","['Action Adventure', 'Fantasy']","As a young boy, Link is tricked by Ganondorf, ...",https://sandbox.oxylabs.io/products/1
1,Super Mario Galaxy,"91,99 €","['Action', 'Platformer', '3D']",[Metacritic's 2007 Wii Game of the Year] The u...,https://sandbox.oxylabs.io/products/2
2,Super Mario Galaxy 2,"91,99 €","['Action', 'Platformer', '3D']","Super Mario Galaxy 2, the sequel to the galaxy...",https://sandbox.oxylabs.io/products/3
3,Metroid Prime,"89,99 €","['Action', 'Shooter', 'First-Person', 'Sci-Fi']",Samus returns in a new mission to unravel the ...,https://sandbox.oxylabs.io/products/4
4,Super Mario Odyssey,"89,99 €","['Action', 'Platformer', '3D']",New Evolution of Mario Sandbox-Style Gameplay....,https://sandbox.oxylabs.io/products/5
5,Halo: Combat Evolved,"87,99 €","['Action', 'Shooter', 'First-Person', 'Sci-Fi']","Enter the mysterious world of Halo, an alien p...",https://sandbox.oxylabs.io/products/6
6,The House in Fata Morgana - Dreams of the Reve...,"83,99 €","['Adventure', 'Visual Novel']",A gothic suspense tale set in a cursed mansion...,https://sandbox.oxylabs.io/products/7
7,NFL 2K1,"62,99 €","['Sports', 'Traditional', 'Football', 'Sim']","In the end, NFL 2K1 is a deeper, more refined ...",https://sandbox.oxylabs.io/products/8
8,Uncharted 2: Among Thieves,"88,99 €","['Action Adventure', 'Modern', 'Linear']",Fortune hunter Nathan Drake returns in Unchart...,https://sandbox.oxylabs.io/products/9
9,Tekken 3,"91,99 €","['Action', 'Fighting', '3D']","An ancient evil force has reawakened, attackin...",https://sandbox.oxylabs.io/products/10
10,The Legend of Zelda: The Wind Waker,"90,99 €","['Action Adventure', 'Fantasy']",In this ninth entry in the Legend of Zelda ser...,https://sandbox.oxylabs.io/products/11
11,Gran Turismo,"86,99 €","['Driving', 'Racing', 'GT / Street']",Welcome to the most advanced racing game ever ...,https://sandbox.oxylabs.io/products/12
12,Metal Gear Solid 2: Sons of Liberty,"88,99 €","['Action Adventure', 'Modern']","Since the incident on Shadow Moses Island, Met...",https://sandbox.oxylabs.io/products/13
13,Grand Theft Auto Double Pack,"81,99 €","['Miscellaneous', 'Compilation']",From the dark and seedy streets of Liberty Cit...,https://sandbox.oxylabs.io/products/14
14,Baldur's Gate II: Shadows of Amn,"91,99 €","['Role-Playing', 'PC-style RPG', 'Western-Style']",An epic continuation of the story that began i...,https://sandbox.oxylabs.io/products/15
15,Tetris Effect: Connected,"88,99 €","['Puzzle', 'Stacking']",Tetris Effect: Connected is the original Tetri...,https://sandbox.oxylabs.io/products/16
16,The Legend of Zelda Collector's Edition,"89,99 €","['Action Adventure', 'Fantasy']",Receive Four Complete Classic Zelda games all ...,https://sandbox.oxylabs.io/products/17
17,Gran Turismo 3: A-Spec,"84,99 €","['Driving', 'Racing', 'GT / Street']",With the addition of two new courses (a downto...,https://sandbox.oxylabs.io/products/18
18,The Legend of Zelda: A Link to the Past,"90,99 €","['Action Adventure', 'Fantasy']",Now you have a link to one of the greatest adv...,https://sandbox.oxylabs.io/products/19
19,The Legend of Zelda: Majora's Mask,"91,99 €","['Action Adventure', 'Fantasy']",Thrown into a parallel world by the mischievou...,https://sandbox.oxylabs.io/products/20
20,The Last of Us,"92,99 €","['Modern', 'Adventure', 'General', 'Action Adv...",Twenty years after a pandemic radically transf...,https://sandbox.oxylabs.io/products/21
21,Persona 5 Royal,"84,99 €","['Role-Playing', 'Japanese-Style']",Prepare for an all-new RPG experience in Perso...,https://sandbox.oxylabs.io/products/22
22,The Last of Us Remastered,"92,99 €","['Action Adventure', 'General', 'Modern']",The Last of Us has been rebuilt for the PlaySt...,https://sandbox.oxylabs.io/products/23
23,The Legend of Zelda: Ocarina of Time 3D,"90,99 €","['Miscellaneous', 'Fantasy', 'Compilation', 'A...",The Legend of Zelda: Ocarina of Time 3D takes ...,https://sandbox.oxylabs.io/products/24
24,Chrono Cross,"88,99 €","['Role-Playing', 'Console-style RPG']",Featuring a storyline developed by the creator...,https://sandbox.oxylabs.io/products/25
25,Gears of War,"84,99 €","['Action', 'Shooter', 'Third-Person', 'Sci-Fi'...",Gears of War blends tactical action with survi...,https://sandbox.oxylabs.io/products/26
26,Sid Meier's Civilization II,"88,99 €","['Strategy', 'Turn-Based', 'Historic', 'Genera...",An empire-building turn-based strategy game. T...,https://sandbox.oxylabs.io/products/27
27,Halo 3,"81,99 €","['Action', 'Shooter', 'First-Person', 'Sci-Fi'...",Halo 3 is the third game in the Halo Trilogy a...,https://sandbox.oxylabs.io/products/28
28,Ninja Gaiden Black,"88,99 €","['Action Adventure', 'Fantasy']",In Ninja Gaiden Black you can reprise the role...,https://sandbox.oxylabs.io/products/29
29,Super Mario Advance 4: Super Mario Bros. 3,"89,99 €","['Action', 'Platformer', '2D']","A combination of exciting platforming action, ...",https://sandbox.oxylabs.io/products/30
30,Jet Grind Radio,"83,99 €","['Action', 'Platformer', '3D']","Join a graffiti crew, stamp your territory and...",https://sandbox.oxylabs.io/products/31
31,Grim Fandango,"91,99 €","['Adventure', 'General', '3D', 'Third-Person',...",Something's rotten in the Land of Dead and you...,https://sandbox.oxylabs.io/products/32

In [30]:
# 2.connect database
conn=mysql.connector.connect(
    host="localhost",
    user="root",
    password="piyush@16",
    database="products_db"
)
cursor=conn.cursor()

In [31]:
query = """
INSERT INTO items (title, price, category, description, links)
VALUES (%s, %s, %s, %s, %s)
"""

In [38]:
for _,row in df.iterrows():
    Price = row["Price"].replace("€", "").replace(",", ".").strip()
    values=[
        row["Title"],
        float(Price),
        str(row["Category"]),
        row["Description"],
        row["Links"]
    ]
    cursor.execute(query,values)

In [39]:
conn.commit()

In [40]:
cursor.close()
conn.close()